# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('ID', models.AutoField(db_column='ID', max_length=20, primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(auto_now_add=True, db_column='Time', null=True)),
                ('Object', models.CharField(blank=True, db_column='Object', max_length=255, null=True)),
                ('Operation', models.CharField(db_column='Operation', max_length=255)),
                ('Detail', models.CharField(blank=True, db_column='Detail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(db_column='Key', max_length=255)),
                ('TTL', models.IntegerField(blank=True, default=3600, null=True)),
                ('Type', models.CharField(db_column='Type', default='A', max_length=255)),
                ('Value', models.CharField(db_column='Value', max_length=255)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='Name', max_length=255, unique=True)),
                ('Type', models.CharField(db_column='Type', default='Forward', max_length=255)),
                ('Switch', models.CharField(db_column='Switch', max_length=255)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.AddField(
            model_name='records',
            name='ZoneName',
            field=models.ForeignKey(db_column='ZoneName', on_delete=django.db.models.deletion.CASCADE, to='dnspool.zones', to_field='Name'),
        ),
    ]
